pub mod action;
pub mod attachment;
pub mod auth;
#[cfg(feature = "captcha")]
pub mod captcha;
pub mod crud;
pub mod dashboard;
pub mod database;
pub mod groups;
pub mod health;
pub mod menu;
pub mod permission;
pub mod plugin;
pub mod schedule;
pub mod settings;
pub mod users;
pub mod view;
pub mod ws;
