[package]
name = "ingjoo-infra"
version.workspace = true
edition.workspace = true
description = "莺竹框架基础设施 — ScaffDb, Auth, Storage, SMS, Email, Captcha 参考实现"
license = "MIT"
keywords = ["ingjoo", "infra", "auth", "storage"]
categories = ["web-programming", "authentication"]

[features]
default = ["db", "auth"]
full = ["db", "auth", "email", "sms", "captcha", "s3", "content-filter", "data-mask", "vector-pg", "signature"]
mock = []
db = ["sqlx"]
auth = ["argon2", "jsonwebtoken", "sha2", "chrono", "rand"]
email = ["lettre"]
sms = ["reqwest", "hmac", "sha2", "hex", "chrono"]
captcha = ["image", "rand", "base64"]
s3 = ["aws-sdk-s3", "aws-config"]
content-filter = []
data-mask = ["aes-gcm", "base64", "rand"]
vector-pg = ["sqlx"]
signature = ["hmac", "sha2", "hex", "chrono"]

[dependencies]
ingjoo-core = { path = "../ingjoo-core" }
ingjoo-security = { path = "../ingjoo-security" }
ingjoo-cache = { path = "../ingjoo-cache" }
ingjoo-queue = { path = "../ingjoo-queue" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
axum.workspace = true
tower-http.workspace = true
async-trait.workspace = true
uuid.workspace = true
futures-util.workspace = true

sqlx = { workspace = true, optional = true }
argon2 = { workspace = true, optional = true }
jsonwebtoken = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
hmac = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
image = { workspace = true, optional = true }
lettre = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }

[dependencies.aes-gcm]
workspace = true
optional = true

[dependencies.aws-sdk-s3]
workspace = true
optional = true

[dependencies.aws-config]
workspace = true
optional = true

[dev-dependencies]
ingjoo-core = { path = "../ingjoo-core" }
ingjoo-macros = { path = "../ingjoo-macros" }
tokio.workspace = true
serde_json.workspace = true
tower.workspace = true
http.workspace = true
tempfile = "3"
